# Site settings

title: shiyunx
#remote_theme: "jekyll/minima@1e8a445"
remote_theme: jekyll/minima

url: "https://shiyunx.github.io" # Corrected URL to match your GitHub Pages domain (assuming shiyunx.github.io)
github_username: shiyunx # Optional: Your GitHub username


# Header pages for top navigation
header_pages:
  - about.md
  - projects.md
  - blog.md # Include this ONLY if you create a 'blog.md' file for a separate blog link
# Layout
show_excerpts: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/ # <--- CRITICALLY CORRECTED: Use the placeholder
   
